# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regex.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegexUtil(object):
    def setupUi(self, RegexUtil):
        RegexUtil.setObjectName("RegexUtil")
        RegexUtil.resize(990, 621)
        self.centralwidget = QtWidgets.QWidget(RegexUtil)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tab)
        self.formLayout_2.setObjectName("formLayout_2")
        self.regular_lable = QtWidgets.QLabel(self.tab)
        self.regular_lable.setObjectName("regular_lable")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.regular_lable)
        self.regular_input = QtWidgets.QTextEdit(self.tab)
        self.regular_input.setObjectName("regular_input")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.regular_input)
        self.str_lable = QtWidgets.QLabel(self.tab)
        self.str_lable.setObjectName("str_lable")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.str_lable)
        self.str_input = QtWidgets.QTextEdit(self.tab)
        self.str_input.setObjectName("str_input")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.str_input)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.result_lable = QtWidgets.QLabel(self.tab)
        self.result_lable.setObjectName("result_lable")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.result_lable)
        self.result_output = QtWidgets.QTextBrowser(self.tab)
        self.result_output.setObjectName("result_output")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.result_output)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.tab_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.dic_input = QtWidgets.QTextEdit(self.tab_2)
        self.dic_input.setObjectName("dic_input")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.dic_input)
        self.tabWidget.addTab(self.tab_2, "")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.tabWidget)
        RegexUtil.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RegexUtil)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 990, 26))
        self.menubar.setObjectName("menubar")
        RegexUtil.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RegexUtil)
        self.statusbar.setObjectName("statusbar")
        RegexUtil.setStatusBar(self.statusbar)

        self.retranslateUi(RegexUtil)
        self.tabWidget.setCurrentIndex(0)
        self.regular_input.textChanged.connect(RegexUtil.regexTest)
        self.str_input.textChanged.connect(RegexUtil.regexTest)
        QtCore.QMetaObject.connectSlotsByName(RegexUtil)

    def retranslateUi(self, RegexUtil):
        _translate = QtCore.QCoreApplication.translate
        RegexUtil.setWindowTitle(_translate("RegexUtil", "MainWindow"))
        self.regular_lable.setText(_translate("RegexUtil", "正则表达式:"))
        self.str_lable.setText(_translate("RegexUtil", "字符串："))
        self.result_lable.setText(_translate("RegexUtil", "结果:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("RegexUtil", "正则测试"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("RegexUtil", "字典配置"))
