# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sceneSelect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sceneDialog(object):
    def setupUi(self, sceneDialog):
        sceneDialog.setObjectName("sceneDialog")
        sceneDialog.resize(372, 154)
        self.scene_list = QtWidgets.QComboBox(sceneDialog)
        self.scene_list.setGeometry(QtCore.QRect(20, 50, 281, 31))
        self.scene_list.setObjectName("scene_list")

        self.retranslateUi(sceneDialog)
        self.scene_list.activated['QString'].connect(sceneDialog.selectScene)
        QtCore.QMetaObject.connectSlotsByName(sceneDialog)

    def retranslateUi(self, sceneDialog):
        _translate = QtCore.QCoreApplication.translate
        sceneDialog.setWindowTitle(_translate("sceneDialog", "Dialog"))
